# Site settings
title:          뉴오프 기술 블로그
description:    "뉴오프의 기술 블로그입니다."
url:            new-off.github.io

# Author
author:
  name:         Newoff
  email:        admin@new-off.com
  url:          

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: admin@new-off.com
  github: https://github.com/new-off
  twitter: https://twitter.com
  linkedin: https://linkedin.com
